### ISSUE TITLE
offsetTop error

### ISSUE THREAD

**Issue by filipesilva** [athensresearch/athens#1543] opened 2021-08-18 09:18 UTC
[https://discord.com/channels/708122962422792194/708124156113321985/877235497926287380](https://cdn.discordapp.com/attachments/708124156113321985/877235495103524954/Screen_Shot_2021-08-17_at_21.00.28.png)

**Comment by neotyk** [comment] 2021-08-19 09:32
We need more steps to reproduce

**Comment by juniusfree** [comment] 2021-08-19 12:34
I'm able to reproduce this by zooming in, then scrolling down on the daily page.

This also seems related to #1492 

![image](https://user-images.githubusercontent.com/8164667/130068970-125588de-c99c-41b1-a1ba-57a383a910d9.png)

**Comment by juniusfree** [comment] 2021-08-20 08:08
I can't reproduce this issue consistently unless I remove the "daily-notes" id directly. I suggest closing for now until we find a more consistent way to reproduce.

**Comment by filipesilva** [comment] 2021-08-20 09:01
Maybe this only happens when the page is not created or something?

**Comment by juniusfree** [comment] 2021-08-20 09:40
@filipesilva Yes. The problem is I can't find those scenarios where the whole daily page fails.

https://github.com/athensresearch/athens/blob/765d6fc1ed56feae1cdc5077c2b2410ae7fd71c1/src/cljs/athens/views/pages/daily_notes.cljs#L65-L73

**Closed** 2022-01-19 13:52 UTC
Labels: t/bug, r/rtc, f/regression
