### ISSUE TITLE
Selection of multiple blocks behaviour (no "deselect")

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1279] opened 2021-06-03 13:25 UTC
**Problem**
When selecting multiple blocks, going "forward" should increase the selected area, but going "backwards" should reduce it.
If I select multiple blocks from bottom to top, for example, and I go too high, then if I bring my mouse down I'm expecting the top blocks to start deselecting, which is not the case right now.

**Screenshots/Demo**
Example below with first a view of Roam behaviour (which feels right) and then Athens behaviour (which feels wrong)

https://user-images.githubusercontent.com/24638389/120652153-11653400-c4b2-11eb-807f-11b97d3c1adb.mov

**Athens Version**
1.0.0-BETA.86 - Intel OSX 10.15.7

**Comment by tangjeff0** [comment] 2021-06-06 21:27
Closed by #1274

**Comment by Limezy** [comment] 2021-06-07 07:53
Hi @tangjeff0 on my side I still have the exact same issue with beta 88

**Comment by tangjeff0** [comment] 2021-06-07 13:32
That's odd, I'm not able to reproduce. Can you share a demo and also share the plain the text that you used so we can try to reproduce?

**Comment by Limezy** [comment] 2021-06-07 16:00
@tangjeff0 sure, please find below :

https://user-images.githubusercontent.com/24638389/121051716-447a3100-c7ec-11eb-8ffd-50d48df52242.mov

The text is a basic nesting of basic blocks. Checked in the daily page and in normal page : 
- A
    - A1
    - A2
        - A2A
        - A2B
        - A2C
            - A2C1
- B
- C
    - C1
- D
    - D1
        - D1A
            - D1A1

**Comment by tangjeff0** [comment] 2021-06-07 17:57
Not able to repro on my M1 Mac: https://www.loom.com/share/63016f5341584d5588e33cd2ffd2ac72

Maybe try hard refresh `cmd-shift-R`or clearing stylefy

@Limezy

**Comment by Limezy** [comment] 2021-06-07 20:36
Tried to hard refresh, and also tried to clear stylefy cache, nothing changed.

But are we really talking about the same thing ? My point is that when keeping my mouse clic pressed and going up to make a selection, if I then turn back and go down with my cursor, then the top blocks will start to be deselected, just like what you can see on Roam in my first video.

At no moment your videos show what I'm expected to see !

**Comment by tangjeff0** [comment] 2021-06-07 20:38
@Limezy I understand now. I thought you meant no deselect from clicking on the block _after_ letting go.

I see now that what you mean - clicking down (_not letting go_) and moving mouse up and down should deselect. I agree that this is the expected behavior. cc @neotyk

**Comment by Limezy** [comment] 2021-06-08 15:08
@tangjeff0 Yes exactly ! Sorry my initial comment may not have clear enough !

**Comment by Limezy** [comment] 2021-06-08 15:08
@tangjeff0 Yes exactly ! Sorry my initial comment may not have clear enough !

**Comment by tangjeff0** [comment] 2021-06-09 22:13
Not your fault! Difficult to communicate digitally. The click's can be tricky to catch. Assigning to @neotyk

**Closed** 2021-07-26 11:14 UTC
Labels: t/bug

**Comment by Limezy** [comment] 2021-07-26 14:10
Thanks 👍
