### ISSUE TITLE
`enter + tab` in quick succession causes duplication of terms

### ISSUE THREAD

**Issue by ddauber** [athensresearch/athens#872] opened 2021-03-24 09:37 UTC
**Problem**

When you try to move parts of a block into a new child block via `enter` and then shortly after hit `tab` to indent, it results in a duplicate of whatever was to the right of the cursor before hitting `enter`.

I assume the problem lies in the latency in keystroke recognition. Presumably, if the keystrokes are coming in too swiftly, they are not properly captured. It still does create the desired result for the new block, but the block above (parent) still contains the text that is now a child block.

**Athens Version**
Mac M1 1.0.0-BETA.60

**Comment by tangjeff0** [comment] 2021-03-28 17:03
I thought this was fixed in a previous commit. Can you demo an example @ddauber ?

**Comment by ddauber** [comment] 2021-03-31 16:30
@tangjeff0, here is an example. It is not a problem if you take it slow. However, if you type more swiftly this is the result.

https://user-images.githubusercontent.com/62331069/113178480-89ab4100-9246-11eb-9610-2b4d8dddfe15.mp4

Thanks for looking into it.

**Comment by sid597** [comment] 2021-06-10 23:02
@ddauber Is this still an issue? I checked it thoroughly in beta.89 can't reproduce this, I think this issue is fixed. I am closing this for now please create a new issue with a comment to this one if this still exists.

**Closed by sid597** 2021-06-10 23:02 UTC
Labels: f/blocks

**Comment by ddauber** [comment] 2021-06-11 11:37
@sid597 It looks good now. It also works on my machine with beta 88, tough. 😉
