### ISSUE TITLE
syntax error: invalid regular expression given adjacent forward-slash and open-paren

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#1308] opened 2021-06-08 19:08 UTC
### Discussed in https://github.com/athensresearch/athens/discussions/867

<div type='discussions-op-text'>

<sup>Originally posted by **phrohdoh** March 22, 2021</sup>
(*edit*: observed on Athens 1.0.0-beta.60)

to reproduce type out the following in a block: `/(f` (`f` is just an example, perhaps the user is going to reference "fred")

<img width="973" alt="Screen Shot 2021-03-22 at 9 16 04 AM" src="https://user-images.githubusercontent.com/4861023/112003812-3bcc6580-8aef-11eb-9613-3cb2a00d90a5.png">

as you can see from the error message, `/(f/` is what is being read as a regex (even though in Athens I have `/(|)`, read `|` as the cursor)

note that, for example, `meet w/ (` works as desired

some questions I've come up with:
- why is this happening? are we using `eval` (😱) somewhere?
- what can we do to _not_ interpret user-entered text as a JS regex?</div>

**Comment by sid597** [comment] 2021-06-11 03:13
removed os/windows label because that implies bug is only in windows, but I can reproduce in Ubuntu, I think this is os independent so no label or a label os/all should be used.

**Comment by tangjeff0** [comment] 2021-06-13 17:37
closed by #1287

**Closed by tangjeff0** 2021-06-13 17:37 UTC
Labels: f/parser, t/bug
