### ISSUE TITLE
Daily Notes Scroll Position Jumps too far, doesn't go back consistently.

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#533] opened 2021-01-03 02:15 UTC
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

When in Daily Notes, 
- scroll position jumps too many days when coming across prior day with content. 
- after experiencing jump, can't return to latest (blank) Daily Notes entry unless I reset the view by clicking the Daily Notes button.

This seems like a different problem than #235 . **See video**

**Expected Behavior**

In Daily Notes, scroll should go to previous day (in reverse consecutive order).

**Dependencies**

- Athens: 1.0.0-beta25
- browser: 
- JVM:
- node.js: 

**To Reproduce**

Try having empty entries for the past couple days, and content for the ~3 days ago.

**Screenshots**

https://user-images.githubusercontent.com/297435/103470378-84615780-4d26-11eb-8e62-22877700d80a.mov

**Comment by seltzered** [comment] 2021-01-03 02:19
Actually may be related to #235 :

<img width="912" alt="Screen Shot 2021-01-02 at 6 17 59 PM" src="https://user-images.githubusercontent.com/297435/103470423-fcc81880-4d26-11eb-9cdf-8d928dc7d9a6.png">

**Comment by tangjeff0** [comment] 2021-01-18 21:55
#235 should be resolved now, however, I never tested this functionality while going from the new year. Will need to follow up on this.

**Comment by sid597** [comment] 2021-06-10 00:24
Can't reproduce, seems this is resolved. Closing for now

**Closed by sid597** 2021-06-10 00:24 UTC
Labels: t/bug
