### ISSUE TITLE
Close, maximize, minimize buttons not working

### ISSUE THREAD

**Issue by weckd** [athensresearch/athens#1890] opened 2021-12-04 21:11 UTC
**Problem**
Close, maxmize, minimize buttons not working,
Platform: Windows 10
**Screenshots/Demo**

![__05_December_2021_2978](https://user-images.githubusercontent.com/85646724/144724673-61ba0bda-d10a-4c5a-9b8d-3fa32441028b.gif)
**Athens Version**
2.0.0-Beta.3
working on 1.0.0

**Comment by weckd** [comment] 2021-12-05 14:59
Not sure what the problem was but its working now.

**Comment by weckd** [comment] 2021-12-05 14:59
sorry closed by mistake

**Comment by nsriv** [comment] 2021-12-06 22:34
Have been experiencing the same behavior since 1.0.0-alpha.rtc.38 on Windows 10 as well.

**Comment by nsvrana** [comment] 2021-12-09 19:14
This is a dupe of (the poorly named) issue #1714.

**Comment by sid597** [comment] 2021-12-17 06:22
@nsvrana @nsriv @weckd This issue is fixed in athens 2.0.0-beta.5 you can download the new client [here](https://github.com/athensresearch/athens/releases/tag/v2.0.0-beta.5) 

Thank you @weckd  for the PR :)

**Closed by sid597** 2021-12-17 06:22 UTC
