### ISSUE TITLE
queries, just like the queries in Roam

### ISSUE THREAD

**Issue by jmartinezheras** [athensresearch/athens#738] opened 2021-03-04 15:15 UTC
Queries in Roam are quite powerful as it allow to automatically populate content based on conditions
https://roamresearch.com/#/app/RoamTutorial/page/rGQtGsDho

A similar functionality will also be useful in Athens

https://discord.com/channels/708122962422792194/800439780910563358/816342080401833984

**Comment by tangjeff0** [comment] 2021-03-05 01:19
Duplicate of #644

**Closed by tangjeff0** 2021-03-05 01:19 UTC
